### ISSUE TITLE
any planned love for 2.70

### ISSUE THREAD

**Issue by Jdabb** [PS5Dev/PS5-UMTX-Jailbreak#2]
It seems like a strange firmware that not many people are on. I didn't want it to be overlooked, so I'm opening an issue. Apologies if this isn't the correct way to request this.

**Comment by nintendont-fanboy** [comment]
We think we have 2.70 working.  You can test it out using Echo Stretch's site.

**Comment by gorshco** [comment]
Added via [`09379a4` (#4)](https://github.com/PS5Dev/PS5-UMTX-Jailbreak/pull/4/commits/09379a41c22b86b5b15a2f0f7dad4e46457d99c6), pending commit.
